In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("titanic.csv")

In [3]:
df

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.0,1,1,16.7000
11,1,1,Miss. Elizabeth Bonnell,female,58.0,0,0,26.5500
12,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.0500
13,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.2750
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.0,0,0,16.0000
16,0,3,Master. Eugene Rice,male,2.0,4,1,29.1250
17,1,2,Mr. Charles Eugene Williams,male,23.0,0,0,13.0000
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000
19,1,3,Mrs. Fatima Masselmani,female,22.0,0,0,7.2250
20,0,2,Mr. Joseph J Fynney,male,35.0,0,0,26.0000
21,1,2,Mr. Lawrence Beesley,male,34.0,0,0,13.0000
22,1,3,Miss. Anna McGowan,female,15.0,0,0,8.0292
23,1,1,Mr. William Thompson Sloper,male,28.0,0,0,35.5000
24,0,3,Miss. Torborg Danira Palsson,female,8.0,3,1,21.0750
25,1,3,Mrs. Carl Oscar (Selma Augusta Emilia Johansso...,female,38.0,1,5,31.3875
26,0,3,Mr. Farred Chehab Emir,male,26.0,0,0,7.2250
27,0,1,Mr. Charles Alexander Fortune,male,19.0,3,2,263.0000
28,1,3,Miss. Ellen O'Dwyer,female,24.0,0,0,7.8792
29,0,3,Mr. Lalio Todoroff,male,23.0,0,0,7.8958
...,...,...,...,...,...,...,...,...
857,0,2,Mr. Frederick Edward Giles,male,21.0,1,0,11.5000
858,1,1,Mrs. Frederick Joel (Margaret Welles Barron) S...,female,48.0,0,0,25.9292
859,0,3,Miss. Dorothy Edith Sage,female,14.0,8,2,69.5500
860,0,2,Mr. John William Gill,male,24.0,0,0,13.0000
861,1,2,Mrs. (Karolina) Bystrom,female,42.0,0,0,13.0000
862,1,2,Miss. Asuncion Duran y More,female,27.0,1,0,13.8583
863,0,1,Mr. Washington Augustus II Roebling,male,31.0,0,0,50.4958
864,0,3,Mr. Philemon van Melkebeke,male,23.0,0,0,9.5000
865,1,3,Master. Harold Theodor Johnson,male,4.0,1,1,11.1333
866,0,3,Mr. Cerin Balkic,male,26.0,0,0,7.8958
867,1,1,Mrs. Richard Leonard (Sallie Monypeny) Beckwith,female,47.0,1,1,52.5542
868,0,1,Mr. Frans Olof Carlsson,male,33.0,0,0,5.0000
869,0,3,Mr. Victor Vander Cruyssen,male,47.0,0,0,9.0000
870,1,2,Mrs. Samuel (Hannah Wizosky) Abelson,female,28.0,1,0,24.0000
871,1,3,Miss. Adele Kiamie Najib,female,15.0,0,0,7.2250
872,0,3,Mr. Alfred Ossian Gustafsson,male,20.0,0,0,9.8458
873,0,3,Mr. Nedelio Petroff,male,19.0,0,0,7.8958
874,0,3,Mr. Kristo Laleff,male,23.0,0,0,7.8958
875,1,1,Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,female,56.0,0,1,83.1583
876,1,2,Mrs. William (Imanita Parrish Hall) Shelley,female,25.0,0,1,26.0000
877,0,3,Mr. Johann Markun,male,33.0,0,0,7.8958
878,0,3,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167
879,0,2,Mr. Frederick James Banfield,male,28.0,0,0,10.5000
880,0,3,Mr. Henry Jr Sutehall,male,25.0,0,0,7.0500
881,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [4]:
x=df.iloc[:,0:].values

In [5]:
x

array([[0, 3, 'Mr. Owen Harris Braund', ..., 1, 0, 7.25],
       [1, 1, 'Mrs. John Bradley (Florence Briggs Thayer) Cumings', ...,
        1, 0, 71.2833],
       [1, 3, 'Miss. Laina Heikkinen', ..., 0, 0, 7.925],
       ...,
       [0, 3, 'Miss. Catherine Helen Johnston', ..., 1, 2, 23.45],
       [1, 1, 'Mr. Karl Howell Behr', ..., 0, 0, 30.0],
       [0, 3, 'Mr. Patrick Dooley', ..., 0, 0, 7.75]], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
# converting sex column into int 
x[:,3]=le.fit_transform(x[:,3])

In [9]:
x # 1 is for male and 0 is for female

array([[0, 3, 'Mr. Owen Harris Braund', ..., 1, 0, 7.25],
       [1, 1, 'Mrs. John Bradley (Florence Briggs Thayer) Cumings', ...,
        1, 0, 71.2833],
       [1, 3, 'Miss. Laina Heikkinen', ..., 0, 0, 7.925],
       ...,
       [0, 3, 'Miss. Catherine Helen Johnston', ..., 1, 2, 23.45],
       [1, 1, 'Mr. Karl Howell Behr', ..., 0, 0, 30.0],
       [0, 3, 'Mr. Patrick Dooley', ..., 0, 0, 7.75]], dtype=object)

In [10]:
x[:,2]=le.fit_transform(x[:,2])

In [11]:
x

array([[0, 3, 601, ..., 1, 0, 7.25],
       [1, 1, 822, ..., 1, 0, 71.2833],
       [1, 3, 171, ..., 0, 0, 7.925],
       ...,
       [0, 3, 99, ..., 1, 2, 23.45],
       [1, 1, 524, ..., 0, 0, 30.0],
       [0, 3, 605, ..., 0, 0, 7.75]], dtype=object)

In [12]:
# now using OneHotEncoder on survived column 
from sklearn.preprocessing import OneHotEncoder

In [13]:
firstcl=OneHotEncoder(categorical_features=[0])

In [14]:
x=firstcl.fit_transform(x).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

In [15]:
x.astype(int)

array([[ 1,  0,  3, ...,  1,  0,  7],
       [ 0,  1,  1, ...,  1,  0, 71],
       [ 0,  1,  3, ...,  0,  0,  7],
       ...,
       [ 1,  0,  3, ...,  1,  2, 23],
       [ 0,  1,  1, ...,  0,  0, 30],
       [ 1,  0,  3, ...,  0,  0,  7]])

In [16]:
features=x

In [17]:
label=x[:,0]

In [18]:
label1=np.where(label==1,'dead',label)

In [19]:
label1=np.where(label1==0,'survived',label)

/home/ubuntu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.

In [20]:
label=np.where(label==1,'dead',label)
label

array(['dead', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0',
       '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead', '0.0',
       'dead', '0.0', 'dead', '0.0', '0.0', '0.0', 'dead', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead',
       'dead', '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', '0.0',
       'dead', 'dead', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0',
       '0.0', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead', 'dead', '0.0',
       'dead', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead', 'dead',
       '0.0', '0.0', 'dead', '0.0', '0.0', 'dead', '0.0', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', '0.0', 'dead', '0.0', 'dead',
       '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0', '0.0',
       'dead', 'dead', 'dead', '0.0', 'dead', 'dead', 'dead', 'dead',
       '0.0', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead',
       'dead', 'dead', '0.0', 'dead', 'dead', 'dead', '0.0', '0.0',
       'dead', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       '0.0', '0.0', 'dead', '0.0', '0.0', 'dead', 'dead', '0.0', 'dead',
       '0.0', '0.0', '0.0', '0.0', 'dead', 'dead', '0.0', 'dead', 'dead',
       'dead', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', '0.0', '0.0',
       'dead', '0.0', 'dead', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0',
       'dead', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead', '0.0',
       'dead', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', 'dead',
       'dead', 'dead', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', 'dead', 'dead', 'dead', 'dead', 'dead', '0.0', '0.0', '0.0',
       'dead', '0.0', '0.0', 'dead', '0.0', '0.0', 'dead', 'dead', 'dead',
       '0.0', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0',
       'dead', '0.0', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', '0.0', '0.0', '0.0', '0.0', 'dead', '0.0', 'dead',
       '0.0', '0.0', '0.0', 'dead', '0.0', '0.0', '0.0', 'dead', 'dead',
       'dead', '0.0', '0.0', 'dead', '0.0', '0.0', 'dead', 'dead', '0.0',
       '0.0', 'dead', '0.0', 'dead', '0.0', '0.0', '0.0', '0.0', 'dead',
       'dead', 'dead', '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0',
       '0.0', 'dead', 'dead', 'dead', '0.0', '0.0', '0.0', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead',
       '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       '0.0', '0.0', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead',
       '0.0', '0.0', 'dead', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0',
       'dead', 'dead', 'dead', '0.0', 'dead', '0.0', '0.0', '0.0', 'dead',
       '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead',
       'dead', 'dead', '0.0', 'dead', '0.0', 'dead', '0.0', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', '0.0', '0.0',
       'dead', '0.0', '0.0', '0.0', '0.0', 'dead', 'dead', '0.0', 'dead',
       '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead',
       '0.0', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead',
       '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead', '0.0',
       'dead', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       '0.0', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       '0.0', 'dead', '0.0', '0.0', 'dead', '0.0', '0.0', 'dead', '0.0',
       '0.0', 'dead', 'dead', '0.0', 'dead', '0.0', 'dead', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', 'dead',
       '0.0', 'dead', 'dead', '0.0', 'dead', '0.0', 'dead', '0.0', 'dead',
       '0.0', '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', '0.0',
       'dead', '0.0', '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', '0.0',
       'dead', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', '0.0', '0.0', '0.0', '0.0', '0.0',
       'dead', 'dead', '0.0', '0.0', 'dead', '0.0', '0.0', '0.0', 'dead',
       'dead', 'dead', '0.0', 'dead', '0.0', 'dead', 'dead', 'dead',
       '0.0', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead',
       '0.0', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0',
       '0.0', '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', 'dead',
       'dead', '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead',
       'dead', 'dead', '0.0', 'dead', 'dead', '0.0', 'dead', '0.0',
       'dead', 'dead', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead',
       '0.0', 'dead', '0.0', '0.0', '0.0', 'dead', '0.0', 'dead', '0.0',
       'dead', '0.0', 'dead', '0.0', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead',
       'dead', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead', '0.0',
       'dead', 'dead', 'dead', '0.0', 'dead', '0.0', 'dead', '0.0',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', '0.0',
       '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead',
       'dead', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0', '0.0',
       '0.0', '0.0', '0.0', 'dead', '0.0', 'dead', 'dead', 'dead', '0.0',
       '0.0', 'dead', '0.0', 'dead', 'dead', 'dead', '0.0', 'dead', '0.0',
       '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', '0.0', 'dead', 'dead', '0.0', 'dead', '0.0',
       'dead', '0.0', 'dead', 'dead', '0.0', 'dead', 'dead', '0.0', '0.0',
       'dead', 'dead', '0.0', '0.0', 'dead', 'dead', 'dead', '0.0',
       'dead', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead',
       'dead', '0.0', 'dead', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead',
       'dead', '0.0', 'dead', '0.0', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead', 'dead',
       '0.0', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', '0.0',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', '0.0', '0.0', 'dead', '0.0', 'dead', 'dead',
       'dead', '0.0', '0.0', '0.0', '0.0', '0.0', 'dead', 'dead', 'dead',
       '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead', '0.0', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', '0.0', 'dead', 'dead',
       'dead', '0.0', 'dead', '0.0', '0.0', '0.0', '0.0', 'dead', 'dead',
       'dead', '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead', '0.0',
       'dead', '0.0', 'dead', 'dead', '0.0', '0.0', 'dead', 'dead',
       'dead', '0.0', '0.0', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', '0.0', 'dead', '0.0', 'dead'], dtype='<U32')

In [21]:
l=label[:,]

In [22]:
l=np.where(l=='0.0','survived',l)

In [23]:
l

array(['dead', 'survived', 'survived', 'survived', 'dead', 'dead', 'dead',
       'dead', 'survived', 'survived', 'survived', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived',
       'dead', 'survived', 'survived', 'survived', 'dead', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'survived', 'survived', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'survived', 'dead', 'dead',
       'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead',
       'survived', 'dead', 'survived', 'survived', 'survived', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'survived', 'survived',
       'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived',
       'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead',
       'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'survived', 'survived', 'survived', 'survived',
       'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'survived', 'survived', 'dead', 'survived', 'survived',
       'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'survived', 'survived', 'survived', 'survived', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'survived',
       'survived', 'survived', 'dead', 'survived', 'dead', 'survived',
       'survived', 'survived', 'dead', 'survived', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived',
       'survived', 'dead', 'dead', 'survived', 'survived', 'dead',
       'survived', 'dead', 'survived', 'survived', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'survived', 'survived', 'survived', 'survived', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead',
       'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'survived', 'survived', 'survived', 'survived',
       'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'survived', 'survived',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'survived', 'dead', 'survived', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'survived', 'dead', 'survived', 'survived', 'survived', 'survived',
       'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'survived', 'survived',
       'survived', 'survived', 'survived', 'survived', 'dead', 'dead',
       'dead', 'survived', 'dead', 'survived', 'dead', 'survived',
       'survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead',
       'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'survived', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'survived',
       'dead', 'survived', 'survived', 'dead', 'survived', 'survived',
       'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead',
       'survived', 'dead', 'survived', 'dead', 'survived', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived',
       'dead', 'survived', 'survived', 'dead', 'dead', 'survived',
       'survived', 'dead', 'survived', 'dead', 'survived', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'survived', 'survived', 'survived', 'survived',
       'dead', 'dead', 'survived', 'survived', 'dead', 'survived',
       'survived', 'survived', 'dead', 'dead', 'dead', 'survived', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'survived', 'survived', 'dead', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead',
       'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead',
       'survived', 'survived', 'survived', 'dead', 'survived', 'dead',
       'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived',
       'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'survived', 'survived', 'survived',
       'survived', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead',
       'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead',
       'survived', 'survived', 'survived', 'survived', 'survived', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'dead', 'survived',
       'survived', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'survived',
       'survived', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead',
       'survived', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'survived', 'survived', 'survived', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived',
       'survived', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'survived', 'survived', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'survived', 'survived', 'survived',
       'survived', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead',
       'survived', 'survived', 'dead', 'dead', 'survived', 'dead', 'dead',
       'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead',
       'survived', 'dead', 'survived', 'survived', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead',
       'dead', 'survived', 'survived', 'dead', 'dead', 'dead', 'survived',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'survived', 'dead'], dtype='<U32')

In [25]:
from sklearn.model_selection import train_test_split

In [28]:
train_data,train_test,label_train,label_test=train_test_split(features,l,test_size=0.2)

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
kclf=KNeighborsClassifier(n_neighbors=5)

In [31]:
ktrained=kclf.fit(train_data,label_train )

In [32]:
predict_output=ktrained.predict(train_test)

In [33]:
predict_output

array(['survived', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived',
       'survived', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead',
       'survived', 'survived', 'survived', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'survived', 'survived', 'dead',
       'dead', 'survived', 'survived', 'survived', 'dead', 'survived',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead',
       'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'survived',
       'dead', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead',
       'dead', 'survived', 'survived', 'dead', 'dead', 'survived',
       'survived', 'survived', 'survived', 'survived', 'survived', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'survived', 'dead', 'survived', 'dead', 'dead', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'survived',
       'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'survived', 'dead', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'survived', 'survived', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'dead', 'dead', 'survived', 'dead',
       'dead', 'dead', 'dead'], dtype='<U32')

In [34]:
label_test

array(['survived', 'survived', 'survived', 'dead', 'dead', 'dead',
       'survived', 'survived', 'dead', 'survived', 'survived', 'dead',
       'survived', 'dead', 'survived', 'dead', 'survived', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'dead', 'survived', 'dead',
       'dead', 'dead', 'survived', 'survived', 'survived', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'survived', 'survived', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'survived', 'survived',
       'dead', 'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead',
       'survived', 'survived', 'survived', 'survived', 'dead', 'survived',
       'dead', 'survived', 'dead', 'dead', 'dead', 'survived', 'survived',
       'dead', 'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'survived',
       'survived', 'survived', 'survived', 'survived', 'dead', 'survived',
       'dead', 'survived', 'dead', 'dead', 'survived', 'survived',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived',
       'survived', 'survived', 'survived', 'dead', 'survived', 'dead',
       'dead', 'dead', 'dead', 'dead', 'dead', 'survived', 'dead', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'survived', 'survived', 'dead',
       'dead', 'survived', 'dead', 'dead', 'dead', 'dead', 'survived',
       'dead', 'dead', 'dead', 'survived', 'survived', 'dead', 'dead',
       'dead', 'survived', 'survived', 'survived', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'dead', 'dead', 'dead', 'dead',
       'survived', 'dead', 'dead', 'survived', 'survived', 'dead', 'dead',
       'dead'], dtype='<U32')

In [35]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(label_test,predict_output)

0.7865168539325843